server.port=9090

# Database Configuration - use 'postgres' as hostname (Docker service name)
spring.datasource.url=jdbc:postgresql://postgres:5432/wallet_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# Security & Webhook Keys
jwt.secret=MfZc/es3ycx+D4nwLap0XX1BnFONlc3N0hGkhMtwwks=
jwt.expiration=86400000
payment.webhook.secret=uK9V7XzR8pQWm+JbN4kL2vYx6tG3sF1hDq0wO9zZ8xY=
refresh.token.expiration=604800000

# Redis Configuration - use 'redis' as hostname (Docker service name)
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=2000ms

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.file.path=/app/logs
logging.level.org.apache.kafka=WARN
logging.level.org.apache.zookeeper=WARN