server.port=9090

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Security & Webhook Keys
jwt.secret=MfZc/es3ycx+D4nwLap0XX1BnFONlc3N0hGkhMtwwks=
jwt.expiration=86400000
payment.webhook.secret=uK9V7XzR8pQWm+JbN4kL2vYx6tG3sF1hDq0wO9zZ8xY=

# Swagger & API Documentation Paths
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Local Logging Paths (Fixed for Windows development)
logging.file.path=./logs

# Framework Noise Muting
logging.level.org.apache.kafka=WARN
logging.level.org.apache.zookeeper=WARN